# Generated by Django 5.1.7 on 2026-03-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('apply', 'Apply'), ('skip', 'Skip'), ('save', 'Save')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_events', to='jobs.jobposting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_events', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('match_score', models.PositiveIntegerField(default=0)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('submission_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'job', 'method')},
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.jobposting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='profiles.candidateprofile')),
            ],
            options={
                'unique_together': {('profile', 'job')},
            },
        ),
    ]
